### ISSUE TITLE
BUG: Shortcuts swallowed on Mac in iPython notebook's terminal

### ISSUE THREAD

**Issue by jakirkham** [takluyver/terminado#16]
Moved from here ( https://github.com/ipython/ipython/issues/8623 ) based on @Carreau's suggestion. If it needs to be pushed higher up, further please let me know.

When trying to using shortcuts on Mac using iPython notebook's terminal, they appear not to work as intended e.g. (copy `⌘+C` and paste `⌘+V`). Generally, they end up being swallowed with no effect.

**Comment by takluyver** [comment]
See chjj/term.js#37 . Sorry, I know there's a lot of pieces fitting together here, but this still isn't the right one. Terminado provides a Python backend, term.js is the terminal emulator frontend.

**Comment by jakirkham** [comment]
Thanks for the ref. Sorry to bug you about this.

**Comment by takluyver** [comment]
No problem - sorry you had to run around different packages.

**Comment by jakirkham** [comment]
@takluyver, so it looks like that PR was accepted.
