### ISSUE TITLE
ENH: Scrollbar needed for iPython notebook's terminal

### ISSUE THREAD

**Issue by jakirkham** [takluyver/terminado#17]
Moved from here ( https://github.com/ipython/ipython/issues/8624 ) based on @Carreau's suggestion. If it needs to be pushed higher up, further please let me know.

It would be nice to have more direct/exact control of scroll when the mouse wheel doesn't cut it.

**Comment by takluyver** [comment]
Again, I think this is a term.js issue. But I don't know how easily fixable it is; I think the scrollback buffer of terminals works somewhat differently from scrollable areas in HTML. So you can check for an issue there, if you like, but given the overall development speed of term.js, it's probably not going to be fixed very soon.

**Comment by jakirkham** [comment]
It looks like this issue ( https://github.com/chjj/term.js/issues/45 ) is most relevant. Closing this...
