### ISSUE TITLE
terminado seems to ignore shell

### ISSUE THREAD

**Issue by twiecki** [takluyver/terminado#2]
When launching a terminal I always get sh even though `/bin/bash` is set in `passwd`.

**Comment by dsblank** [comment]
I see this too. Wonder if it is related to the race condition from #4 ?

**Comment by takluyver** [comment]
Is this in the terminado demos or in IPython? The demos are hardcoded to use bash, and ipython should respect the $SHELL environment variable.

This is not related to the race condition, as far as I can see.

**Comment by dsblank** [comment]
I'm seeing this running ipython-master and jupyterhub-master. But I think it is because:

```
! echo $SHELL
```
is empty... but not sure why...

**Comment by dsblank** [comment]
I was able to address this with:
```
SHELL=/bin/bash jupyterhub
```

**Comment by dsblank** [comment]
Actually, that worked for notebook, but not jupyterhub. This worked:

```
SHELL=/bin/bash ipython notebook
```

but not this:

```
SHELL=/bin/bash jupyterhub
```
I'll try a full export in the start-up script.

**Comment by dsblank** [comment]
This also did not work:
```
export SHELL=/bin/bash 
jupyterhub
```
Please advise on how to get bash to be terminal shell.

**Comment by takluyver** [comment]
I don't know - this isn't a terminado issue, it's a question of how to get Jupyterhub to start the individual notebook servers with a given environment variable set. Min might be able to help you with that. Note that the answer will almost certainly depend on your Jupyterhub setup, i.e. whether notebook servers run locally in Unix user accounts, in docker containers, on separate machines, etc.
