### ISSUE TITLE
Terminado running on WSL

### ISSUE THREAD

**Issue by dhirschfeld** [takluyver/terminado#32]
![image](https://cloud.githubusercontent.com/assets/881019/17543071/5473ba48-5f11-11e6-9fab-4fdaf20891ce.png)

Woot! :stuck_out_tongue_winking_eye:

**Comment by dhirschfeld** [comment]
Not really an issue - just wanted to say it *is* possible! A couple of issues I found (YMMV):
 * I had to disable my firewall
 * I had to be running bash as admin
 * I had to press `q` to get out of w3m?

...and sometimes it still didn't work

**Comment by dhirschfeld** [comment]
...the part about not working reliably may have just been me not knowing how to use w3m.
Replacing
```
run_and_show_browser("http://localhost:8765/", term_manager)
```
with
```
    try:
        tornado.ioloop.IOLoop.instance().start()
    finally:
        term_manager.shutdown()
```
made it work reliably!

**Comment by dhirschfeld** [comment]
It seems it was just w3m that was making it not work - I can run without admin and with the firewall turned on. ping however doesn't work without admin which is a known issue IIUC

**Comment by takluyver** [comment]
Nice, thanks for letting me know!
