### ISSUE TITLE
Terminal Sandbox

### ISSUE THREAD

**Issue by aintbrokedontfix** [takluyver/terminado#33]
is there a way to sandbox the terminal to the user home?

**Comment by takluyver** [comment]
That's up to whatever program (e.g. bash) you run in the terminal. Terminado just lets a web page talk to it. I don't know much about sandboxing, but you could use standard unix permissions to limit what the user can see, or run the terminals inside containers/VMs.

**Comment by aintbrokedontfix** [comment]
Thanks!
