### ISSUE TITLE
Race condition causes first shell prompt to be not sent

### ISSUE THREAD

**Issue by payne92** [takluyver/terminado#4]
When creating a new terminal in the IPython notebook, the initial shell prompt is not shown (on my system) -- there's just a blank terminal window.  If you hit return, you get the prompt twice, as if the first shell prompt was queued but not presented.  

Otherwise, the terminal works fine.

The problem is due a race condition.

What seems to be happening is the shell process is spawning and generating the initial prompt BEFORE any clients are registered with the terminal object to pass stdout back to the user.  

See:  https://github.com/takluyver/terminado/blob/master/terminado/websocket.py#L81

From websocket.open()

        self.terminal = self.term_manager.get_terminal(url_component)
        self.terminal.clients.append(self)

get_terminal() is spawning the shell process, and registering the read handler pty_read(), which is firing with the shell prompt stdout before the client object is appended.

Looking at the code, one fix is to move the calls to .start_reading() call up out of the various terminal managers and into TermSocket.open(), AFTER setup is complete.  I've tested one instance of this and it fixes the problem, but I'm not familiar enough with the code to judge it as a general solution that doesn't break other things.

**Comment by takluyver** [comment]
I've also noticed this. I haven't fixed it yet because each terminal can
have multiple clients, which may connect at later times. So it's not
generally as simple as starting reading after a client connects. I've been
thinking about having a short output buffer in terminado which would be
replayed to a new client when it connects. I will look into this soon.

**Comment by payne92** [comment]
A few ideas:

+ Have an optional initial client (or list) that can be passed down from get_teriminal() that can be used to initialize the client structure.

+ Refactor things so that clients are added and removed through an abstraction that also manages the read callbacks (adding them when the first client is added, and tearing them down when the last client is removed)

Of course, I'm not familiar with this code.
